name: npm CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: Build-Next
      uses: ricardobiundo/NextPagesAction@1.0.2
      with:
        username: 'pxzxj'
        reponame: 'json-flatter-ui'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
